### DISCUSSION TITLE
How to know if a device is down (vs offline) in Home Assistant?

### DISCUSSION THREAD

**Discussion by teranex** [netalertx/NetAlertX#1057] [General]
I have NetAlertX setup with MQTT integration to Home Assistant. I'm looking for a way to know which devices are 'down'? I might be overlooking something, but as far as I can see the data which is provided to HA regarding online/offline state is only `is_present` (and `is_home`), which is not enough information to be able to make the distinction between offline and down devices?
I would like to make an overview in HA for my down devices, using the auto-entities card (https://github.com/thomasloven/lovelace-auto-entities), but without devices that are expected to be regularly offline (such as smartphones etc).

**Comment by jokob-sk** [comment]
Hi,

There will be a a new attribute in the next release that can help you filter devices that are marked as Alert Down

![image](https://github.com/user-attachments/assets/d8d09088-e097-4365-958d-0a373558e5ba)

Hope this works

**Comment by teranex** [comment]
@jokob-sk that looks exactly like what I was looking for. Thanks a lot!

**Reply by jokob-sk** [reply]
Thanks for confirming!

**Comment by teranex** [comment]
I just upgraded to the latest version and integrated it in Home Assistant. Works nicely :)

I have added a Mushroom Chip which only appears when there is at least 1 device offline:

![20250526_001](https://github.com/user-attachments/assets/180988c2-53f0-4c0b-a43c-ded18e5c655a)

And also an overview card using [auto-entities](https://github.com/thomasloven/lovelace-auto-entities) to show which devices are offline (could use some more formatting and tweaking but it does the job):

![20250526_002](https://github.com/user-attachments/assets/f0aff677-4c0d-4106-a1b6-3ff17aad3b36)

For anyone interested:
Code for the Mushroom Chip:

```yaml
type: custom:mushroom-chips-card
chips:
  - type: conditional
    conditions:
      - condition: numeric_state
        entity: sensor.netalertx_down
        above: 0
    chip:
      type: template
      icon: mdi:network-off-outline
      icon_color: red
      content: "Network devices down: {{ states('sensor.netalertx_down') }}"
      entity: sensor.netalertx_down

```

Code for the overview of down devices:

```yaml
type: custom:auto-entities
card:
  type: entities
  title: Offline network devices
filter:
  include:
    - and:
        - attributes:
            alert_down: "1"
        - state: not_home
  exclude: []
```

**Reply by jokob-sk** [reply]
Thank you for sharing this, these things, when stuff improves and works, make me smile 🙂

**Comment by waterwingz** [comment]
I'm struggling a bit to understand how to implement this. Newbie question maybe?

Do you need to manually create an new entity for every device you want to monitor? Maybe by adding sensor entries to the mqtt section of configuration.yaml where their values comes from mqtt entry netalertx/device_tracker/mac_xx-xx-xx-xx-xx-xx/state_ ? 

That seems painful if you have a big network of nodes you want to display the "down" status for. Is there a better way that I am missing?

TIA

**Reply by jokob-sk** [reply]
Hi, AFAIK no manual attributes/entities are necessary. There is an attribute on the device_tracker taht indicates if a device is flagged as a down device when offline. you need to  enable MQTT at first: https://jokob-sk.github.io/NetAlertX/HOME_ASSISTANT/?h=mqtt Then you follow the above thread: https://github.com/jokob-sk/NetAlertX/discussions/1057#discussioncomment-13276247

**Reply by jokob-sk** [reply]
You can also check this doc: https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/_publisher_mqtt/

**Reply by waterwingz** [reply]
Thanks for the quick reply.   

I have MQTT installed and running under Home Assistant.  I use it for many things unrelated to NetAlertX   I also have MQTT enabled in NetAlertX and it sends node status information through my MQTT broker as expected.   

My problem is that I have to create individual entities per node to fetch and use the MQTT information within HA, which is pretty much unusable once you have more than ~25 nodes being monitored.  

For example, in the first code snippet from @teranex , he uses a discrete entity called **sensor.netalertx_down** . I'm guessing that's an MQTT entity he manually created something like this :

```
mqtt:
    - sensor:
        - name: "netalertx_down"
          state_topic: "netalertx/sensor/nodes/state"
          value_template: "{{ value_json.down | int | string }}" 
```

 to read and make available the number of nodes down ?
 
 In a similiar manner, I can figure out the "away" state of each node by adding code like this (for each device) to configuration.yaml : 

```
mqtt:
    - sensor:
        - name: "Sensor Node State"
          state_topic: "netalertx/device_tracker/mac_61_01_84_34_ba_95/state"
          unique_id: "netalertx002"  
```
and that works. But it means creating similar entities for each node that I care about.  Ouch.

It feels like there should be an easier way and I just don't have enough HA experience to figure it out.

**Reply by jokob-sk** [reply]
Hi,

I'm really a bit confused. The sensors and attributes should be available on the MQTT entity created by NAX:

![img](https://i.imgur.com/OfgIUeo.gif)

**Reply by waterwingz** [reply]
okay - I think that's my problem.  NAX is not creating entities for each of the nodes it finds.  So I've missed something in the configuration process. 

**Edit :**  it looks like I need to setup each node manually in the MQTT integration as devices rather than add them to configuration.yaml .   So still a manual process where I need to click ( + Add MQTT Device ) manually for each of my 60+ nodes?  Or is there some way for NAX to do that automatically?

**Reply by jokob-sk** [reply]
Do you have MQTT_SEND_DEVICES=True ?

**Reply by waterwingz** [reply]
Yes - it's checked in the Settings -> Publisher section for MQTT publisher

That causes MQTT messages for each node to be passed to the broker - I can see them with the MQTT Explorer app.  But there is no corresponding entity in HA to do anything with it.   It's like there was a setup step I missed where NAX was supposed to create HAS entities for each device it found on the network but it skipped that step?

**Reply by waterwingz** [reply]
One detail that might matter?  I installed NAX as a Home assistant add-on (from the alexbelgium repo) 

[https://github.com/alexbelgium/hassio-addons/tree/master/netalertx](url)

Does that affect how MQTT works or needs to be setup?

**Reply by jokob-sk** [reply]
It should not. Can you please post your app.log of the plugin execution with LOG_LEVEL set to debug and your MQTT settings?

**Reply by waterwingz** [reply]
app.log file after a "Restart Server" and "Purge Log" button pushed,  several mqtt updates had been sent to the broker, and a monitored device had gone down :  https://pastebin.com/BsyR6Lax 

MQTT configuration screen shot :  https://imgur.com/a/rNt5pkC

**Reply by waterwingz** [reply]
Likely unrelated or a different issue,  but when I had previously changed the **MQTT topic root**  to something other than **_homeassistant_** (such as **_netalertx_**)  then I see mqtt updates at the broker (via MQTT Explorer) made regularly to topic  **_netalertx_** and sometimes to **_homeassistant_** as well.  Why the duplicate root topics?

That maybe nothing or may be a clue?

**Reply by jokob-sk** [reply]
Thanks for the logs, they seem to be what is expected. If you have changed the topic recently then that might cause the issue. NAX remembers which devices were synced over so old entries might not have been updated. I'd recommend deleting existing MQTT entries in NAX and on the broker) and trying to let the sync run again. 

- Deleting of devices is not handled automatically. Please use [MQTT Explorer](https://mqtt-explorer.com/) to delete devices in the broker (Home Assistant), if needed.
- https://github.com/jokob-sk/NetAlertX/tree/main/front/plugins/_publisher_mqtt#forcing-an-update

By default MQTT_DEVICE_ID='netalertx' so not sure if your 'nodes' value would cause any HA conflict.

I would also recommend checking out the MQTT explorer or HA MQTT debug to see if all expected information gets synced over.

**Reply by waterwingz** [reply]
Maybe I'm being thick here so I'll try a simple question?   

In the example link you posted above showing how to force an update for MQTT,  there is an screenshot showing a device called  
_**PC-B LAN (House)**_  
with a list of sensor names ( l**ast_ip, is_present, mac_accdress, is_new** etc) associated with that device.  

If you wanted to display the value of   **is_present**    for   **PC-B LAN (House)**   in a simple sensor card on a HA Dashboard,  what would the entity name be for referencing that device and state ?  (( I hope that makes sense?) 

TIA

**Reply by jokob-sk** [reply]
I'd just do it this way: 
![ezgif-222cb8e7496b69](https://github.com/user-attachments/assets/1b73dc87-69b2-4eca-8906-8cc79134fc7e)

the generated yaml is:


```yaml
type: entities
entities:
  - entity: sensor.pc_b_wifi_first_connection
    name: First_connection
  - entity: device_tracker.pc_b_wifi_is_home
    name: Is_home
  - entity: sensor.pc_b_wifi_is_new
    name: Is_new
  - entity: binary_sensor.pc_b_wifi_is_present
    name: Is_present
  - entity: sensor.pc_b_wifi_last_connection
    name: Last_connection
  - entity: sensor.pc_b_wifi_last_ip
    name: Last_ip
  - entity: sensor.pc_b_wifi_mac_address
    name: Mac_address
  - entity: sensor.pc_b_wifi_vendor
    name: Vendor
title: PC - B WiFi
```
