### DISCUSSION TITLE
Problem: "no such table: PH.network"

### DISCUSSION THREAD

**Discussion by xeion** [netalertx/NetAlertX#116] [Q&A]
Hi,

Im trying to run Pi.Alert in docker but im unable to start it.. 
I always get the error

Traceback (most recent call last):
  File "/home/pi/pialert/back/pialert.py", line 2352, in <module>
    sys.exit(main())       
  File "/home/pi/pialert/back/pialert.py", line 187, in main
    scan_network() 
    reporting = copy_pihole_network() or reporting
  File "/home/pi/pialert/back/pialert.py", line 703, in copy_pihole_network
    sql.execute ("""INSERT INTO PiHole_Network (PH_MAC, PH_Vendor, PH_LastQuery,
sqlite3.OperationalError: no such table: PH.network
Scan Devices
    ScanCycle:1
    Timestamp:2022-12-14 13:44:00

I have downloaded the database from https://github.com/jokob-sk/Pi.Alert/blob/main/db/pialert.db?raw=true

**Comment by jokob-sk** [comment]
Hi there,

Looks like you want to use pinhole in your setup.

Can you please share your docker-compose and relevant pialert.conf settings?

Thanks in advance,
j

**Reply by xeion** [reply]
docker-compose.yaml
```
version: "3"
services:
  pialert:
    container_name: pialert
    image: "jokobsk/pi.alert:sha-ccc33bf"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      # pialert
      - /..../pialert/config:/home/pi/pialert/config
      - /..../pialert/db/pialert.db:/home/pi/pialert/db/pialert.db
      #- /..../pialert/run:/run
      # (optional) map an empty file with the name 'setting_darkmode' if you want to force the dark mode on container rebuilt
      - /..../pialert/db/setting_darkmode:/home/pi/pialert/db/setting_darkmode
      # (optional) useful for debugging if you have issues setting up the container
      - /..../pialert/logs:/home/pi/pialert/log
      # pihole integration
      - /..../pihole/etc/pihole-FTL.db:/etc/pihole/pialert-FTL.db
      - /..../pihole/etc/dhcp.leases:/etc/pihole/dhcp.leases
    environment:
      - TZ=Europe/Stockholm
      - HOST_USER_ID=x
      - HOST_USER_GID=y
      - PORT=20211
```

pialert.conf
```
# GENERAL settings
# ----------------------

PIALERT_PATH            = '/home/pi/pialert'
DB_PATH                 = PIALERT_PATH + '/db/pialert.db'
LOG_PATH                = PIALERT_PATH + '/log'
VENDORS_DB              = '/usr/share/arp-scan/ieee-oui.txt'
PRINT_LOG               = False
TIMEZONE                = 'Europe/Stockholm'
PIALERT_WEB_PROTECTION  = False
PIALERT_WEB_PASSWORD    = 'abc'

INCLUDED_SECTIONS       = ['internet', 'new_devices', 'down_devices', 'events']   # Specifies which events trigger notifications. 
                                                                                  # Remove the event type(s) you don't want to get notified on 
                                                                                  # Overrides device-specific settings in the UI.
SCAN_CYCLE_MINUTES      = 5            # delay between scans

# EMAIL settings
# ----------------------
SMTP_SERVER             = 'smtp.gmail.com'
SMTP_PORT               = 587
SMTP_USER               = '...@...'
SMTP_PASS               = 'abc'
SMTP_SKIP_TLS           = False
SMTP_SKIP_LOGIN	        = False

REPORT_MAIL             = True
REPORT_FROM             = 'Pi.Alert <' + SMTP_USER +'>'
REPORT_TO               = '...@...'
REPORT_DEVICE_URL       = 'https://x.y.z/deviceDetails.php?mac='
REPORT_DASHBOARD_URL    = 'https://x.y.z/'

# Webhook settings
# ----------------------
REPORT_WEBHOOK          = False

# Apprise settings
#-----------------------
REPORT_APPRISE          = False
APPRISE_HOST            = 'http://localhost:8000/notify'
APPRISE_URL             = 'mailto://smtp-relay.sendinblue.com:587?from=user@gmail.com&name=apprise&user=user@gmail.com&pass=password&to=user@gmail.com'

# NTFY (https://ntfy.sh/) settings
# ----------------------
REPORT_NTFY             = False

# PUSHSAFER (https://www.pushsafer.com/) settings
# ----------------------
REPORT_PUSHSAFER        = False

# MQTT settings
# ----------------------
REPORT_MQTT             = False

# DynDNS
# ----------------------
DDNS_ACTIVE             = False

# PIHOLE settings
# ----------------------
PIHOLE_ACTIVE           = True
PIHOLE_DB               = '/etc/pihole/pihole-FTL.db'
DHCP_ACTIVE             = False
DHCP_LEASES             = '/etc/pihole/dhcp.leases'

# arp-scan options & samples
# ----------------------
SCAN_SUBNETS    = 'x.y.z.0/24 --interface=ovs_bond0 x.y.a.0/24 --interface=ovs_bond1'

# Maintenance Task Settings
# ----------------------
DAYS_TO_KEEP_EVENTS = 90

```
