### DISCUSSION TITLE
VLAN Tips

### DISCUSSION THREAD

**Discussion by mscreations** [netalertx/NetAlertX#404] [General]
So I thought I'd post some info here for anyone that is struggling with getting VLANs to work with Pi-Alert. I recently had an issue with the way I originally setup Pi-Alert and my Docker machine that took some time to troubleshoot and get ironed out. Originally, I added multiple network adapters in Hyper-V and had the separate VLANs connected to each one using Hyper-V's network setup. Unfortunately, this caused my Docker host to fail to be able to properly network traffic. For some reason, it was creating a route for my network time server/domain controller to every interface and it was causing me to not get synchronized time on my Ubuntu VM which caused issues in Authentik. This led me down the path to try to get this to work as it should.

My setup is as follows: Bare Metal -> Hyper-V on Win Server 2019 -> Ubuntu 22.04 VM -> Docker -> Pi-Alert. My network connections to my switches are configured as trunk and allow all VLANs access to the server. 

My biggest issue that I had was that by default Hyper-V only allows untagged packets through to the VM interface and no VLAN tagged packets get through. As far as I could tell, there was no way to adjust this in the network adapter dialog window. In order to fix this, I had to run in Powershell on my Hyper-V machine: 
```
Set-VMNetworkAdapterVlan -VMName <Docker VM Name> -Trunk -NativeVlanId 0 -AllowedVlanIdList "<comma separated list of vlans>"
```

After that, within the VM, I setup sub-interfaces for each of the VLANs so I could scan them. Since I'm on Ubuntu 22.04 I'm using Netplan.

In /etc/netplan/00-installer-config.yaml, I added my vlan definitions:
```
network:
  ethernets:
    eth0:
      dhcp4: yes
  vlans:
    eth0.2:
      id: 2
      link: eth0
      addresses: [ "192.168.2.2/24" ]
      routes:
        - to: 192.168.2.0/24
          via: 192.168.1.1 
```

After that I ran `sudo netplan apply` and the interfaces were then available to scan in Pi-Alert. In this case, I used `192.168.2.0/24 --interface=eth0.2`
