### DISCUSSION TITLE
Possible to use Traefik (reverse proxy) with Pi.Alert?

### DISCUSSION THREAD

**Discussion by Isegrimm** [netalertx/NetAlertX#449] [Q&A] [answered]
The current reverse proxy support seems to be limited to SWAG, Apache and nginx, as discussed and documented here: https://github.com/jokob-sk/Pi.Alert/discussions/275

Traefik can strip the prefix of a url path (www.domain.com/pialert > www.domain.com) and stores the stripped prefix in a X-Forwarded-Prefix header. This works on the condition that the backend application reads this header to reconstruct the proper url.

With the current version, stripping the prefix results in Pi.Alert attempting to open www.domain.com/devices.php, which doesn't work because Traefik is configured to react on www.domain.com/pialert.
A correct url would be www.domain.com/pialert/devices.php, which can be constructed by using the content of the X-Forwarded-Prefix header.

Any plans to make Pi.Alert work with this method? Or is there another way to make Pi.Alert work with Traefik that I don't know?

**Comment by jokob-sk** [comment]
Hi there,

I'm b really not sure as I'm not using traefik myself.

@cvc90 do you know by any chance?

Thanks,
J

**Reply by cvc90** [reply]
Hello @jokob-sk 

I don't currently use Traefik and can't try certain solutions I can think of.

But if you add the following tags when creating Pi.Alert you should have no problems getting it to work.

    labels:
      - traefik.backend=Pi.Alert # Docker name
      - traefik.frontend.rule=Host:pi.alert.your_domain.com # URL address to access Pi.Alert through Traefik
      - traefik.docker.network=Internal network / External network  #Trafik network name
      - traefik.port=20211 #Port of Pi.Alert

**Reply by jokob-sk** [reply]
@Isegrimm - can you give it a try? Please report back if it works and if you could, write up a short guide so I can include it in the docs

**Reply by jokob-sk** [reply]
thank you @cvc90 🙏

**Reply by Isegrimm** [reply]
Hi @cvc90 

The rule-label you specify is for a url like pialert.domain.com:
`traefik.frontend.rule=Host:pi.alert.your_domain.com`

This will indeed work, but I want it to be reachable at a url like this: www.domain.com/pialert.
When using labels that would look like this:
`traefik.frontend.rule=Host:www.your_domain.com && PathPrefix(/pialert)`

But to make that work, Pi.Alert has to return the proper urls to the browser (for example www.domain.com/pialert/devices.php instead of www.domain.com/devices.php), and so Pi.Alert has to be aware that it's called on a path instead of the root of a domain, which requires either manually specifying the base path (/pialert) in the configuration of Pi.Alert or make Pi.Alert use the X-Forwarded-Prefix header (which is defined by Traefik by using the stripprefix directive and contains '/pialert').

For reference, this is what I have configured for Pi.Alert:
(I'm using a TOML file for the Traefik configuration instead of labels, but I don't think it matters for the configuration)

```
[http.routers]
  [http.routers.pialert-router]
    entryPoints = ["websecure"]
    rule = "Host(`www.domain.com`) && PathPrefix(`/pialert`)"
    service = "pialert-service"
    middlewares = "auth,pialert-stripprefix"
    [http.routers.pialert-router.tls]
       certResolver = "<snip>"
       [[http.routers.pialert-router.tls.domains]]
         main = "www.domain.com"

[http.services]
  [http.services.pialert-service]
    [[http.services.pialert-service.loadBalancer.servers]]
      url = "http://internal-ip-address:20211/"

[http.middlewares]
  [http.middlewares.auth.forwardAuth]
    address = "<snip>"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Name", "Remote-Email"]
  [http.middlewares.pialert-stripprefix.stripprefix]
    prefixes = "/pialert"
    forceSlash = false

```

**Reply by jokob-sk** [reply]
I'm out of my depth here so if someone wants to submit a PR to enable this setup, feel free to do so.

**Reply by cvc90** [reply, marked as answer]
Hi!

I think a possible solution to this problem could be solved as follows.

In the file [/etc/nginx/sites-available/default](https://github.com/jokob-sk/Pi.Alert/blob/main/install/default) of Docker Pi.Alert would add the directive that you mention that Traefik could read them.

add_header X-Forwarded-Prefix "/pialert" always;
proxy_set_header X-Forwarded-Prefix "/pialert";

```
server {
    listen 80 default_server;
    root /var/www/html;
    index index.php;
    #rewrite /pialert/(.*) / permanent;
    add_header X-Forwarded-Prefix "/pialert" always;
    proxy_set_header X-Forwarded-Prefix "/pialert";

  location ~* \.php$ {
    fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    include         fastcgi_params;
    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_connect_timeout 75;
          fastcgi_send_timeout 600;
          fastcgi_read_timeout 600;
  }
}
```

Check what I said, so you can send the PR with the solution.

**Reply by cvc90** [reply]
@Isegrimm can you give it a try? Please report back if it works

**Reply by Isegrimm** [reply]
Hi @cvc90 , apologies for not reacting sooner. I somehow missed the notification.
I will test this later this week and let you know the outcome.

**Reply by Isegrimm** [reply]
Hi @cvc90 , I have made the changes and it works now. Thanks for your help! 😄 
One remark, www.domain.com/pialert/ works but www.domain.com/pialert not, so the trailing / is needed.

**Reply by jokob-sk** [reply]
@Isegrimm can you write up a short guide on how to do it with the correct configuration example so I update the guide?

**Reply by Isegrimm** [reply]
@jokob-sk , assuming the user already has a working Traefik setup, this is what's needed to make Pi.Alert work at a URL like www.domain.com/pialert/. It's partialy just copy-paste from the previous posts, happy to help if you need specific information.

Note: Everything in these configs assumes '**www.domain.com**' as your domainname and '**section31**' as an arbitrary name for your certificate setup. You will have to substitute these with your own.
Also, I use the prefix '**pialert**'. If you want to use another prefix, change it in these files: dynamic.toml and default.

Content of my yaml-file (this is the generic Traefik config, which defines which ports to listen on, redirect http to https and sets up the certificate process).
It also contains Authelia, which I use for authentication.
This part contains nothing specific to Pi.Alert.
```
version: '3.8'

services:
  traefik:
    image: traefik
    container_name: traefik
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--providers.file.filename=/traefik-config/dynamic.toml"
      - "--providers.file.watch=true"
      - "--log.level=ERROR"
      - "--certificatesresolvers.section31.acme.email=postmaster@domain.com"
      - "--certificatesresolvers.section31.acme.storage=/traefik-config/acme.json"
      - "--certificatesresolvers.section31.acme.httpchallenge=true"
      - "--certificatesresolvers.section31.acme.httpchallenge.entrypoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - /appl/docker/traefik/config:/traefik-config
    depends_on:
      - authelia
    restart: unless-stopped
  authelia:
    container_name: authelia
    image: authelia/authelia:latest
    ports:
      - "9091:9091"
    volumes:
      - /appl/docker/authelia:/config
    restart: unless-stopped
```
Snippet of the dynamic.toml file (referenced in the yml-file above) that defines the config for Pi.Alert:
The following are self-defined keywords, everything else is traefik keywords:
- pialert-router
- pialert-service
- auth
- pialert-stripprefix
```
[http.routers]
  [http.routers.pialert-router]
    entryPoints = ["websecure"]
    rule = "Host(`www.domain.com`) && PathPrefix(`/pialert`)"
    service = "pialert-service"
    middlewares = "auth,pialert-stripprefix"
    [http.routers.pialert-router.tls]
       certResolver = "section31"
       [[http.routers.pialert-router.tls.domains]]
         main = "www.domain.com"

[http.services]
  [http.services.pialert-service]
    [[http.services.pialert-service.loadBalancer.servers]]
      url = "http://internal-ip-address:20211/"

[http.middlewares]
  [http.middlewares.auth.forwardAuth]
    address = "http://authelia:9091/api/verify?rd=https://www.domain.com/authelia/"
    trustForwardHeader = true
    authResponseHeaders = ["Remote-User", "Remote-Groups", "Remote-Name", "Remote-Email"]
  [http.middlewares.pialert-stripprefix.stripprefix]
    prefixes = "/pialert"
    forceSlash = false

```
To make Pi.Alert work with this setup I modified the default file at /etc/nginx/sites-available/default in the docker container by copying it to my local filesystem, adding the changes as specified by cvc90 and mounting the new file into the docker container, overwriting the original one. By mapping the file instead of changing the file in-place, the changes persist if an updated dockerimage is pulled. This is also a downside when the default file is updated, so I only use this as a temporary solution, until the dockerimage is updated with this change.

Default-file:
```
server {
    listen 80 default_server;
    root /var/www/html;
    index index.php;
    #rewrite /pialert/(.*) / permanent;
    add_header X-Forwarded-Prefix "/pialert" always;
    proxy_set_header X-Forwarded-Prefix "/pialert";

  location ~* \.php$ {
    fastcgi_pass unix:/run/php/php7.4-fpm.sock;
    include         fastcgi_params;
    fastcgi_param   SCRIPT_FILENAME    $document_root$fastcgi_script_name;
    fastcgi_param   SCRIPT_NAME        $fastcgi_script_name;
    fastcgi_connect_timeout 75;
          fastcgi_send_timeout 600;
          fastcgi_read_timeout 600;
  }
}
```
Mapping the updated file (on the local filesystem at /appl/docker/pialert/default) into the docker container:

```
docker run -d --rm --network=host \
  --name=pi.alert \
  -v /appl/docker/pialert/config:/home/pi/pialert/config \
  -v /appl/docker/pialert/db:/home/pi/pialert/db \
  -v /appl/docker/pialert/default:/etc/nginx/sites-available/default \
  -e TZ=Europe/Amsterdam \
  -e PORT=20211 \
  jokobsk/pi.alert:latest

```
