### DISCUSSION TITLE
Just 2 devices detected [Solved]

### DISCUSSION THREAD

**Discussion by daniel-alomar** [netalertx/NetAlertX#552] [Q&A] [answered]
I have installed Pi.Alert inside a container and running along Pi.hole. Some months ago I have this installations but without containers and pi.alert detect a lot of devices.. but maybe 'cause it was connected directly to pihole since the beginning.

I have not connected yet (I notice I have to map the pihole-FTL.db inside a pialert container folder). But before connected them, I though Pi.Alert should detect more devices than the router and itself... 

My DNS is in my router and almost all devices are connected through the WiFi. 

What's wrong? What I am missing? 

Regards,

P.D.: My configuration:

```
version: "3.92"
services:
  pi.alert:
     container_name: Pi.Alert
     healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
      interval: 5m
      timeout: 10s
      retries: 5     
     volumes:
      - /home/daniel/DockerVol/pialert/config:/home/pi/pialert/config:rw
      - /home/daniel/DockerVol/pialert/db:/home/pi/pialert/db:rw
      - /home/daniel/DockerVol/pialert/log:/home/pi/pialert/front/log:rw
     environment:
      TZ: Europe/Madrid
      PORT: 20211
     network_mode: host
     restart: unless-stopped
     image: jokobsk/pi.alert:latest
```

**Comment by jokob-sk** [comment]
Hi @daniel-alomar 👋

Thanks for using PiAlert,

I assume you have the `ARPSCAN` plugin enabled. If so, make sure you have the `SCAN_SUBNETS` set correctly. Please check this documentation for details:

https://github.com/jokob-sk/Pi.Alert/blob/main/docs/SUBNETS.md

In these cases most often the interface is not set correctly.

Let me know if you need more help,
j

**Comment by daniel-alomar** [comment, marked as answer]
Hi,

This is the first thing I checked:
```
root@Anuk:/# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether b8:27:eb:71:a5:52 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::ba27:ebff:fe71:a552/64 scope link 
       valid_lft forever preferred_lft forever
```
What I have under arp pilaert setup (Previously I had eth1, the default one )
![imatge](https://github.com/jokob-sk/Pi.Alert/assets/15876760/8efa3107-0a57-42da-b63d-90a794f7b2ff)

What I get if I run the command arp inside the container:
![imatge](https://github.com/jokob-sk/Pi.Alert/assets/15876760/6a0783c9-7f58-4aad-9767-f5906f6ea5a3)

BTW, inside the Pialert documentation I found this

> Run iwconfig in your container to find your interface name(s) (e.g.: eth0, eth1).

But the iwconfig command is not installed in the image container

**Reply by jokob-sk** [reply]
Thank you for teh details.

I will update the docs in the next release, thanks for that!

Regarding your issue, can you please provide me with the logs after you enabled `debug` as per [docs](https://github.com/jokob-sk/Pi.Alert/blob/main/docs/DEBUG_TIPS.md)?

Please provide me with the full log file or the section around the ARPSCAN execution? You can search for the following string:

`[Plugins] Processing        : ARPSCAN`

**Reply by jokob-sk** [reply]
Ah, I also noticed you have the mask set to `*.10`. Is that intentional?

![image](https://github.com/jokob-sk/Pi.Alert/assets/96159884/2e057069-3f1d-4561-918f-c194b5f8fcb7)

**Reply by jokob-sk** [reply]
Can you please try to set your mask to the following?

`192.168.1.0/24` and interface to `eth0`

**Comment by daniel-alomar** [comment]
Yeap... that was the problem.. First I didn't notice the interface set was eth1, I read eth0 in the example but the interface added by default was eth1.. maybe this is something confusing.. and when I realize I have to add my interface, I added the IP and not the network.. now Pi.Alert detects more devices.. 

It could be interesting to add a tip to:
1.- Add health status of the container
2.- Map de pihole installation folder to enable the connection between both application.  

This is my setup:

```
version: "3.92"
services:
  pi.alert:
     container_name: Pi.Alert
     healthcheck:
      test: curl -f http://localhost:20211/ || exit 1
      interval: 5m
      timeout: 10s
      retries: 5     
     volumes:
      - /home/daniel/DockerVol/pialert/config:/home/pi/pialert/config:rw
      - /home/daniel/DockerVol/pialert/db:/home/pi/pialert/db:rw
      - /home/daniel/DockerVol/pialert/log:/home/pi/pialert/front/log:rw
      - /home/daniel/DockerVol/pihole/etc-pihole:/etc/pihole/:rw
     environment:
      TZ: Europe/Madrid
      PORT: 20211
      HOST_USER_ID: 1000
      HOST_USER_GID: 1000
     network_mode: host
     restart: unless-stopped
     image: jokobsk/pi.alert:latest
```
