### DISCUSSION TITLE
Docker Support for Plugins?

### DISCUSSION THREAD

**Discussion by APT256** [netalertx/NetAlertX#584] [General]
This is probably a dumb question, but as I am new to Docker and Pi.Alert, here it goes. I have Pi.Alert (tag: jokobsk/pi.alert:latest) running as a Docker image on my Unraid server. It appears to be running fine. I have found some plugins that I would like to try, but I am not sure that they will work in a Docker image because, if I understand correctly, everything added to the original image will be deleted at the next reboot? Now I know there is a way to save some persistent data (i.e. config files, db, etc), so I would think that this could be done for plugins too. Is there an environment variable that contains the path to the plugins directory? If so, I could add this variable to my image, create the folder on persistent storage, and hopefully get the plugins working.

**Comment by jokob-sk** [comment]
Hi @servebeer ,

Could you please let me know where you've found those plugins? I can then write up a guide on how to deploy them in the docker container.

In theory, you should be able to mount the directory to:

`.local/<plugin>:/home/pi/pialert/front/plugins/<plugin>`

The plugin structure should follow: https://github.com/jokob-sk/Pi.Alert/blob/main/front/plugins/README.md#plugin-file-structure-overview

**Comment by APT256** [comment]
@jokob-sk thanks for the offer. Somehow I misplaced the link for the particular plug in that I am interested in. It might be on work computer, so I will check tomorrow and let you know.

**Reply by APT256** [reply]
Well, this stinks... I can't find the link to that plug in. I'll keep looking for it. In the mean-time, would your write-up generic instructions for adding 3rd party plugins?

Thanks!
Jon

**Reply by jokob-sk** [reply]
Hi @servebeer ,

Let me know if you find it again!

The guide is these two steps:

1. Make sure the Plugin adheres to the [plugin structure](https://github.com/jokob-sk/Pi.Alert/blob/main/front/plugins/README.md#plugin-file-structure-overview).
2. Map the plugin to the `:/home/pi/pialert/front/plugins/`  location, e.g.:  `.local/new_plugin:/home/pi/pialert/front/plugins/new_plugin`

**Reply by APT256** [reply]
Thank you!

**Comment by ingoratsdorf** [comment]
There's also the option to copy plugins at container startup. Somewhat a bit of a hack, but seems working well. That way, you can also overwrite existing plugins (if you wanted to)
Just map a user plugin folder alongside the plugin folder in the container and copy files at startup, then call the original init command to start all up.

docker-compose:

```
name: netalertx-dev
services:
  netalertx:
    image: jokobsk/netalertx-dev
    entrypoint:
      - bash
      - -c
      - chown -R nginx:www-data /app/front/user_plugins ; cp -R /app/front/user_plugins/* /app/front/plugins/ ; /init
    [..]
    volumes:
      [..]
      - type: bind
        source: /opt/docker-data/netalertx/user_plugins
        target: /app/front/user_plugins
[..]
```
