### DISCUSSION TITLE
Error connecting to database

### DISCUSSION THREAD

**Discussion by seelk07** [netalertx/NetAlertX#598] [Q&A] [answered]
All of a sudden, I am no longer able to access the web interface.  I believe this occurred after a recent update.  I receive the message "Error connecting to database, will try in 3s".  After pressing OK it still does not connect and produces the same message "Error connecting to database".  Thoughts?

Below is the docker compose file I used.

```yaml
version: "3"
services:
  pialert:
    container_name: pialert
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/pi.alert_dev:latest"
    image: "jokobsk/pi.alert:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - /config/pialert:/home/pi/pialert/config
      - /config/pialert/db:/home/pi/pialert/db
      # (optional) useful for debugging if you have issues setting up the container
      - /config/pialert/logs:/home/pi/pialert/front/log
    environment:
      - TZ=America/New_York
      # - HOST_USER_ID=1000
      # - HOST_USER_GID=1000
      - PORT=20211
```
