### DISCUSSION TITLE
Installation on Raspberry Pi

### DISCUSSION THREAD

**Discussion by kanuto0o** [netalertx/NetAlertX#757] [Q&A] [answered]
I'm trying to install on raspberry pi 3b, but without success here I expose my yaml

```
version: "3.3"
services:
  pialert:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data/config:/app/config
      - ./data/db:/app/db
      - ./data/logs:/app/front/log
    ports:
      - "20211:20211"
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
```
```
version: '3.6'

services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - netalertx_data:/data
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000

volumes:
  netalertx_data
```

```
version: "3"
services:
  netalertx:                                  # ⚠  This has changed (🟡optional) 
    container_name: netalertx                 # ⚠  This has changed (🟡optional) 
    # use the below line if you want to test the latest dev image
    # image: "jokobsk/netalertx-dev:latest" 
    image: "jokobsk/netalertx:latest"         # ⚠  This has changed (🟡optional/🔺required in future) 
    network_mode: "host"        
    restart: unless-stopped
    volumes:
      - local/path/config/app.conf:/app/config/app.conf # ⚠  This has changed (🔺required) 
      - local/path/db/app.db:/app/db/app.db             # ⚠  This has changed (🔺required) 
      # (optional) useful for debugging if you have issues setting up the container
      - local/path/logs:/app/front/log                  # ⚠  This has changed (🟡optional) 
    environment:
      - TZ=Europe/Berlin      
      - PORT=20211
```

```
version: "3.3"

services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    ports:
      - "20211:20211"
    volumes:
      - netalertx_data:/data
    restart: unless-stopped

volumes:
  netalertx_data:

```

```
version: '3.2'

services:
  netalertx:
    image: jokobsk/netalertx:latest
    container_name: netalertx
    restart: always
    ports:
      - "2121:2121"
    volumes:
      - netalertx_data:/data
    environment:
      - TZ=Europe/Madrid
      - PUID=1000
      - PGID=1000

volumes:
  netalertx_data:
```

I have tried all those containers and they all give me the same error

```
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-svscan crashed. Killing everything and exiting.
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
s6-svscan: warning: unable to iopause: Operation not permitted
s6-svscan: warning: executing into .s6-svscan/crash
s6-supervise s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-linux-init-shutdownd: fatal: unable to iopause: Operation not permitted
s6-svscan crashed. Killing everything and exiting.
s6-linux-init-hpr: fatal: unable to reboot(): Operation not permitted
```
Is there a solution or is it impossible to use it on raspberry pi?

**Comment by jokob-sk** [comment]
Hi @kanuto0o ,

I haven't tried running it on a Raspberry PI3 B, but it may be doable. 

What I've noticed is that you are specifying the port mappings. That's not needed as the container is running on the host network. Your compose file should look e.g (notice missing `ports:` section):

```yaml
version: "3.3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data/config:/app/config
      - ./data/db:/app/db
      - ./data/logs:/app/front/log
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
```

if this still doesn't work, you can try to start without mounting folders - just as a test - to see if the issue is permission-related:

```yaml
version: "3.3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
```

if this works, double check the folders have the right permissions and check this guide:

https://github.com/jokob-sk/NetAlertX/blob/main/docs/FILE_PERMISSIONS.md

**Reply by kanuto0o** [reply]
![image](https://github.com/user-attachments/assets/b84571a8-aff8-4ba4-bd25-e520622d28bf)
![image](https://github.com/user-attachments/assets/0e4383d6-300a-4543-9c8a-8c26a4899825)
![image](https://github.com/user-attachments/assets/ce5fe316-aea5-403a-8372-e1bb9e7f59d5)
![image](https://github.com/user-attachments/assets/02073169-37c5-4941-a33e-f0a37f7f76dc)
![image](https://github.com/user-attachments/assets/7a70e36d-19a5-4c07-973c-1be82f0e53c6)
I'm telling you that I didn't have nginx installed, as I have pihole and pialert I don't think that was the problem, even so I installed nginx and changed the port to 9009
![image](https://github.com/user-attachments/assets/5bf037c0-d040-4347-8fb0-8cb8659cf9df)
and as you can see it works.
I added the permissions you indicated and I have tested the 2 containers you provided me and loading cargo but it is not seen in port 20211
So I don't know what the problem is anymore. I've also tried changing port 20211 to 9009 to see if at least that's how it looks.
But without results.

**Reply by jokob-sk** [reply]
Thanks for the additional details!

Can you send me some more info to help you further?

1. What is the command you use to start up the container and what docker-compose.yaml file are you using (please post the content). 
2. Could you please send me a screenshot of the ports the container is using? I'm attaching how the port configuration looks like in Portainer:
![image](https://github.com/user-attachments/assets/32b824f2-8057-4ac0-bf66-fc6d2acd3862)
3. Can you post the startup log that you see in the terminal after you start up the container?
4. Try to ensure that the container has the necessary capabilities. You can add capabilities to the container using the --cap-add flag:
```bash
docker run --cap-add=SYS_ADMIN --cap-add=SYS_BOOT your_image
```
5. Can you post the output you are getting when running this command?
```bash
docker run --rm --network=host \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest
```

**Reply by kanuto0o** [reply]
![image](https://github.com/user-attachments/assets/1c32a8ef-af2e-4e5c-8d93-15a42b885ff3)
[docker-compose(Netalertx).zip](https://github.com/user-attachments/files/16562442/docker-compose.Netalertx.zip)
![image](https://github.com/user-attachments/assets/2f87cb85-8e9f-4a1d-a4b9-6cdc0b345337)
![image](https://github.com/user-attachments/assets/cde0fe1b-f6b8-411b-92fd-63c68e241547)
![image](https://github.com/user-attachments/assets/1d339a0c-21ec-4853-a2f5-56c72f378c49)
I used the docker that you sent me and told me it would work. Then I did what you told me and uploaded screenshots.

**Reply by jokob-sk** [reply]
Running the Docker container with sudo could potentially resolve the issue if the problem stems from insufficient privileges. Here's how you can modify your command to use sudo:

```bash

sudo docker run --rm --network=host \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest
```

However, if running with sudo doesn't resolve the issue, you might need to consider the following alternatives:

 Use the --privileged flag:
  Running the container with the --privileged flag grants the container elevated privileges, which might solve the permission issue.

```bash

sudo docker run --rm --network=host --privileged \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest
```

Modify the security context:
You can try running the container with additional security options, such as --cap-add SYS_ADMIN or --security-opt seccomp=unconfined. These options adjust the security constraints on the container:

```bash

sudo docker run --rm --network=host --cap-add SYS_ADMIN --security-opt seccomp=unconfined \
  -e TZ=Europe/Berlin \
  -e PORT=20211 \
  jokobsk/netalertx:latest
```

Check Docker version and permissions:
Ensure that your Docker installation is up to date and that the user running Docker has the appropriate permissions to manage Docker containers.

**Comment by kanuto0o** [comment, marked as answer]
Hello, I come with new news, after several attempts in the end it was because I had an old version of Raspbian, I updated to the latest one by downloading the image and burning it on the Raspberry and everything works now I have to configure it, use this docker.

```
version: "3.3"
services:
  netalertx:
    container_name: netalertx
    image: "jokobsk/netalertx:latest"
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - ./data/config:/app/config
      - ./data/db:/app/db
      - ./data/logs:/app/front/log
    environment:
      - TZ=Europe/Madrid
      - PORT=20211
```
